# Site settings
title: "bow, ngapain bow?"
email: "ssayabowo@gmail.com"
description: "... Why not?"
baseurl: "/"
url: "bowoekren.github.io"
twitter_username: "bowoekren"
github_username: "bowoekren"
disqus_username: "bowoekren"
#isso_domain: comments.mysite.org

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 10
excerpt_separator: "\n\n\n" # excerpt ends after two blank lines

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
