# Site settings
title: Arief Wibowo W
email: ssayabowo@gmail.com
description: "... Why not?"
baseurl: "/"
url: "http://bowekr.github.io/"
twitter_username: "bowekr"
github_username: "bowekr"
disqus_username: "bowekr"
#isso_domain: comments.mysite.org

# Build settings
#markdown: redcarpet
permalink: /:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
